modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="http://github.com/svenhjol/Charm/issues"
displayURL="https://svenhjol.github.io/Charm/"
license="https://github.com/svenhjol/Charm/blob/master/LICENSE"

[[mods]]
modId="charmonium"
version="${mod_version}"
displayName="Charmonium"
description='''
Ambient sounds and additional music for Charm.
'''
authors="svenhjol, warlordwossman, Coranthes"

[[dependencies.charmonium]]
    modId="forge"
    mandatory=true
    versionRange="[35.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.charmonium]]
    modId="charm"
    mandatory=true
    versionRange="[2.2.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.charmonium]]
    modId="quark"
    mandatory=false
    versionRange="[r2.4,)"
    ordering="AFTER"
    side="BOTH"